### ISSUE TITLE
Make passing the signer optional for gateway operations

### ISSUE THREAD

**Issue by IgorShadurin** [DappyKit/sdk#14]
```
const sdk = new SDK(
        optimismMainnetConfig,
        RpcHelperUtils.convertHDNodeWalletToAccountSigner(window.DappyKit.Wallet.createRandom()),
      )
```

Also, the initialization should be simplified to require only the wallet, instead of the signer.

In some cases no signer needed at all.

**Comment by Imponsomu** [comment]
const sdk = new SDK( optimismMainnetConfig, RpcHelperUtils.convertHDNodeWalletToAccountSigner(window.DappyKit.Wallet.createRandom())
